sudo: false
language: go

cache: false
go:
  - 1.12.x

before_script:
  - go mod tidy
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
    sh -s -- -b $(go env GOPATH)/bin v1.17.1

script:
  - go build -i cmd/core/main.go
  - go test -v -race ./...
  - golangci-lint run -c config/.golangci.yml

install: true

deploy:
  - provider: script
    skip_cleanup: true
    script: bash build/deploy.sh
    on:
      branch: production
